org.gradle.jvmargs=-Xmx6g -Xms256m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -Dkotlin.daemon.jvm.options\="-Xmx6g" -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
android.injected.testOnly=false
org.gradle.parallel=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache-problems=warn
