name: main

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.idea/**'

      # only one run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@main


      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin
          cache: "gradle"

      - name: Set Gradle Conf
        run: |
          mkdir -p ~/.gradle/
          printf '%s\n' \
            'org.gradle.parallel=true' \
            'org.gradle.daemon=true' \
            'org.gradle.jvmargs=-XX:+UseParallelGC -Xmx6g -Xms256m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8' \
            'org.gradle.workers.max=2' \
            'kotlin.incremental=false' \
            'kotlin.compiler.execution.strategy=in-process' \
            'org.gradle.caching=true' \
            'org.gradle.configuration-cache=true' \
            'org.gradle.configuration-cache-problems=warn' \
            > ~/.gradle/gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get VersionCode
        run: |
          version_code=$(git rev-parse --short HEAD)
          echo "version_code: $version_code"
          echo "version_code=$version_code" >> $GITHUB_ENV
          version_number=$(git rev-list --count HEAD)
          echo "version_number: $version_number"
          echo "version_number=$version_number" >> $GITHUB_ENV

      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleRelease \
          --build-cache --parallel \
          -x checkReleaseAarMetadata \
          -x checkKotlinGradlePluginConfigurationErrors \
          -x checkReleaseDuplicateClasses
#        env:
#          KEYSTORE_PATH: "../keystore.jks"
#          KEYSTORE_PASSWORD: 123456
#          KEY_ALIAS: 123456
#          KEY_PASSWORD: 123456

#      - name: Upload Artifacts
#        uses: actions/upload-artifact@main
#        # don't upload the artifacts if it's a pull request
##        if: ${{ !github.event.pull_request }}
#        with:
#          path: './app/build/outputs/**/*.apk'
#          name: build_output_${{ github.event.head_commit.id }}.zip

      - name: 获取当前时间
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY/MM/DD

#      - name: 上传
#        uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "build_android_${{steps.current-time.outputs.formattedTime}}-${{ env.version_code }}"
#          prerelease: true
#          files: ./app/build/outputs/**/*.apk

      - name: Delete Pre-Release
        run: |
          if gh release view beta &>/dev/null; then
            gh release delete beta -y
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update beta tag
        uses: richardsimko/update-tag@main
        with:
          tag_name: beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Pre-Release
        uses: ncipollo/release-action@main
        with:
          name: "build_android_${{steps.current-time.outputs.formattedTime}}-${{ env.version_code }}-${{ env.version_number }}"
          tag: "beta"
          body: "beta ${{steps.current-time.outputs.formattedTime}}-${{ env.version_code }}-${{ env.version_number }}"
          prerelease: true
          artifacts: ./app/build/outputs/**/*.apk

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
